import Link from "next/link";
import { notFound } from "next/navigation";
import { CalendarDays, MapPin, TicketCheck } from "lucide-react";
import { prisma } from "@/lib/prisma";
import { registerParticipant } from "@/app/actions";
export const dynamic = "force-dynamic";

export default async function PublicEventPage({params}:{params:Promise<{slug:string}>}){
  const {slug}=await params;
  const event=await prisma.event.findUnique({where:{slug},include:{ticketTypes:{where:{active:true}},formFields:{where:{enabled:true},orderBy:{sortOrder:"asc"}},consentTerms:true}}).catch(()=>null);
  if(!event) notFound();
  return <main className="min-h-screen bg-slate-50"><header className="border-b bg-white"><div className="mx-auto flex max-w-6xl items-center px-5 py-4"><Link href="/" className="flex items-center gap-2 font-bold"><span className="grid size-9 place-items-center rounded-xl bg-indigo-600 text-white"><TicketCheck size={19}/></span>Eventra</Link></div></header>
    <section className="bg-slate-950 text-white"><div className="mx-auto max-w-6xl px-5 py-14"><span className="rounded-full bg-indigo-500/20 px-3 py-1.5 text-xs font-semibold text-indigo-200">{event.type.replace("_"," ")}</span><h1 className="mt-6 max-w-4xl text-4xl font-black sm:text-6xl">{event.name}</h1><p className="mt-5 max-w-3xl text-lg text-slate-300">{event.description}</p><div className="mt-8 flex flex-wrap gap-5 text-sm text-slate-300"><span className="flex gap-2"><CalendarDays size={18}/>{event.startsAt.toLocaleString("id-ID")}</span><span className="flex gap-2"><MapPin size={18}/>{event.venue}</span></div></div></section>
    <form action={registerParticipant} className="mx-auto grid max-w-6xl gap-7 px-5 py-12 lg:grid-cols-2"><input type="hidden" name="eventId" value={event.id}/><section><h2 className="text-2xl font-bold">Pilih tiket</h2><div className="mt-5 space-y-3">{event.ticketTypes.map((t:any,i:number)=><label key={t.id} className="flex cursor-pointer items-center justify-between rounded-2xl border bg-white p-5"><span><b>{t.name}</b><small className="mt-1 block text-slate-500">Kuota {t.quota}</small></span><span className="flex items-center gap-3"><b>Rp{Number(t.price).toLocaleString("id-ID")}</b><input required defaultChecked={i===0} type="radio" name="ticketTypeId" value={t.id}/></span></label>)}</div></section><section className="rounded-2xl border bg-white p-6"><h2 className="text-xl font-bold">Data peserta</h2><div className="mt-5 grid gap-4"><Field name="fullName" label="Nama lengkap" required/><Field name="email" label="Email" type="email" required/><Field name="phone" label="Nomor telepon"/>{event.formFields.filter((f:any)=>!["full_name","email","phone"].includes(f.key)).map((f:any)=><Field key={f.id} name={f.key} label={f.label} required={f.required}/>)}</div>{event.consentTerms.map((c:any)=><label key={c.id} className="mt-4 flex gap-3 text-sm"><input required={c.required} type="checkbox" name={"consent_"+c.id}/><span><b>{c.title}</b><small className="block text-slate-500">{c.body}</small></span></label>)}<button className="mt-6 w-full rounded-xl bg-indigo-600 px-5 py-3 font-semibold text-white">Lanjutkan pendaftaran</button></section></form>
  </main>
}
function Field({name,label,type="text",required=false}:{name:string;label:string;type?:string;required?:boolean}){return <label className="text-sm font-medium">{label}<input name={name} type={type} required={required} className="mt-2 w-full rounded-xl border border-slate-200 px-4 py-3 outline-none focus:border-indigo-500"/></label>}
