import Link from "next/link";
import { CalendarDays, Check, Clock3, MapPin, ShieldCheck, TicketCheck } from "lucide-react";
import { events } from "@/lib/demo-data";

export default async function PublicEventPage({params}:{params:Promise<{slug:string}>}){
  const {slug}=await params; const event=events.find(e=>e.slug===slug) ?? events[0]; const run=event.type==="FUN_RUN";
  return <main className="min-h-screen bg-[#f7f8fc] text-slate-950"><header className="border-b border-slate-200 bg-white"><div className="mx-auto flex max-w-6xl items-center justify-between px-5 py-4"><Link href="/" className="flex items-center gap-2 font-bold"><span className="grid size-9 place-items-center rounded-xl bg-indigo-600 text-white"><TicketCheck size={19}/></span>Eventra</Link><span className="text-sm text-slate-500">Diselenggarakan oleh <b className="text-slate-800">Aurora Events</b></span></div></header>
    <section className="overflow-hidden bg-slate-950 text-white"><div className="mx-auto grid max-w-6xl gap-10 px-5 py-14 lg:grid-cols-[1.25fr_.75fr] lg:py-20"><div><span className="rounded-full bg-indigo-500/20 px-3 py-1.5 text-xs font-semibold text-indigo-200">{run?"FUN RUN":"SEMINAR / WEBINAR"}</span><h1 className="mt-6 text-4xl font-black tracking-tight sm:text-6xl">{event.name}</h1><p className="mt-5 max-w-2xl text-lg leading-8 text-slate-300">{run?"Mulai pagi dengan energi terbaik, pilih kategori lari Anda, dan nikmati pengalaman bersama komunitas.":"Temukan wawasan praktis dari para pembicara dan terhubung dengan peserta dari berbagai industri."}</p><div className="mt-8 flex flex-wrap gap-5 text-sm text-slate-300"><span className="flex items-center gap-2"><CalendarDays size={18}/>{event.date}</span><span className="flex items-center gap-2"><Clock3 size={18}/>06.00 WITA</span><span className="flex items-center gap-2"><MapPin size={18}/>{event.place}</span></div></div><div className="rounded-3xl bg-gradient-to-br from-indigo-500 to-violet-600 p-7 shadow-2xl"><p className="text-sm text-indigo-100">Tiket mulai dari</p><p className="mt-2 text-3xl font-bold">{run?"Rp175.000":"Rp99.000"}</p><div className="mt-6 space-y-3 text-sm">{["E-ticket dengan QR unik",run?"Registrasi ulang & race pack":"Materi dan sertifikat", "Pembayaran aman"].map(x=><p key={x} className="flex gap-2"><Check size={18}/>{x}</p>)}</div><a href="#tickets" className="mt-7 block rounded-xl bg-white px-5 py-3 text-center font-semibold text-indigo-700">Pilih tiket</a></div></div></section>
    <section id="tickets" className="mx-auto grid max-w-6xl gap-7 px-5 py-12 lg:grid-cols-[1fr_380px]"><div><h2 className="text-2xl font-bold">Pilih tiket</h2><div className="mt-5 space-y-4">{(run?[["5K Fun Run","175.000","243 tersisa"],["10K Challenge","225.000","115 tersisa"]]:[["Online Pass","99.000","284 tersisa"],["Full Access","249.000","42 tersisa"]]).map(([name,price,left])=><article key={name} className="flex items-center justify-between gap-4 rounded-2xl border border-slate-200 bg-white p-5"><div><h3 className="font-semibold">{name}</h3><p className="mt-1 text-sm text-slate-500">{left}</p></div><div className="text-right"><p className="font-bold">Rp{price}</p><button className="mt-2 rounded-lg bg-indigo-600 px-4 py-2 text-sm font-semibold text-white">Pilih</button></div></article>)}</div></div><aside className="h-fit rounded-2xl border border-slate-200 bg-white p-6"><h3 className="font-semibold">Informasi pendaftaran</h3><p className="mt-3 text-sm leading-6 text-slate-500">Form pendaftaran akan menampilkan field sesuai preset dan pengaturan event.</p><div className="mt-5 flex gap-3 rounded-xl bg-emerald-50 p-4 text-sm text-emerald-800"><ShieldCheck className="shrink-0" size={20}/><span>Persetujuan dan persyaratan wajib diperiksa sebelum pembayaran.</span></div></aside></section>
  </main>
}
